trigger: none

parameters:
  - name: runinit
    type: boolean
    default: true
  - name: runfmt
    type: boolean
    default: true
  - name: runvalidate
    type: boolean
    default: true
  - name:  runplan
    type: boolean
    default: true

stages:
  - stage: initStage
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: installJob
        steps:
        - task: TerraformInstaller@1
          displayName: instaaling terraform
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          condition: eq('${{ parameters.runInit }}', true)
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Workload_secure_connection'
            backendAzureRmStorageAccountName: 'demostorage8250'
            backendAzureRmContainerName: 'anujcontainer'
            backendAzureRmKey: 'anuj.tfstate'

        - task: TerraformTask@5
          condition: eq('${{ parameters.runfmt }}', true)
          displayName: terraform fmt
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'Workload_secure_connection'
        
        - task: TerraformTask@5
          condition: eq('${{ parameters.runvalidate }}', true)
          inputs:
            provider: 'azurerm'
            command: 'validate'
  
        - task: TerraformTask@5
          condition: eq('${{ parameters.runplan }}', true)
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Workload_secure_connection'
  - stage:
    dependsOn: initStage
    pool: 'server'
    jobs:
     - job: validJob
       steps:
       - task: ManualValidation@1
         inputs:
           notifyUsers: 'anujsoam07@gmail.com'
           approvers: 'anujsoam07@gmail.com'
           instructions: 'if timeout directly reject for sure.'
           
    
  