trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Workload_secure_connection'
    backendAzureRmStorageAccountName: 'demostorage8250'
    backendAzureRmContainerName: 'anujcontainer'
    backendAzureRmKey: 'anuj.tfstate'